# Download the nuscenes data set and put them to '$PWD/data'.
#   - v1.0-test_meta.tgz
#   - v1.0-test_blobs.tgz
#   - v1.0-mini.tgz
#
# Build the docker image:
#   docker build -t bevdepth_py311_cpu_image -f Dockerfile_py311-cpu .
#
# Run the container:
#   docker run --name bevdepth_py311_cpu_container --shm-size 64gb --mount src=$PWD,target=/home/BEVDepth,type=bind -it bevdepth_py311_cpu_image /bin/bash
#
# Attach the container:
#   docker container attach bevdepth_py311_cpu_container

FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update -y
RUN apt upgrade -y
RUN apt install -y build-essential \
  cmake \
  ninja-build \
  libssl-dev \
  git \
  wget \
  vim \
  # for python3.11
  libffi-dev \
  zlib1g-dev \
  # for mmcv
  ffmpeg \
  libsm6 \
  libxext6 \
  # for BEVDepth
  lzma \
  liblzma-dev \
  libbz2-dev

# Install Python3.11 for torch2.4.0.
ENV CPYTHON_ROOT="/home/cpython"
WORKDIR /home
RUN git clone https://github.com/python/cpython.git
WORKDIR $CPYTHON_ROOT
RUN git checkout v3.11.3
RUN ./configure
RUN make -j $(nproc)
RUN make install

WORKDIR /home
CMD ["/bin/sh"]

# Activate Python virtual environment:
#   python3 -m venv pyvenv
#   source /home/BEVDepth/pyvenv/bin/activate

# pip install --upgrade pip
# pip install torch-mlir==20240701.138 --find-links https://github.com/llvm/torch-mlir-release/releases/expanded_assets/dev-wheels

# Install mmcv:
#   git clone https://github.com/open-mmlab/mmcv.git
#   cd mmcv
#   git checkout v2.1.0
#   MMCV_WITH_OPS=1 pip install -e .
#   pip install pycocotools
#   pip install shapely
#   pip install scipy
#   pip install terminaltables
#   pip install tqdm

# Install mmdetection:
#   git clone https://github.com/open-mmlab/mmdetection.git
#   cd mmdetection
#   git checkout v3.3.0
#   pip install wheel
#   pip install --no-dependencies --no-build-isolation .

# error

# pip install --upgrade pip
# pip install torch==2.4.0
# pip install mmcv
# pip install mmdet
# pip install mmdet3d